name: Transfer Via SSH
on:
  push:
    branches:
      - main
jobs:
  sendFiles:
    name: Transfer Files
    runs-on: ubuntu-latest
    env:
      LOCAL_DIRECTORY: ./
      # The full name of the remote directory will be parsed in the first step
      REMOTE_DIRECTORY: ""
    steps:
      - name: Parse Remote Directory Name
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: echo "REMOTE_DIRECTORY=/var/www/html/$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)" >> $GITHUB_ENV
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Send Files
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.LOCAL_DIRECTORY }}
          remote: ${{ env.REMOTE_DIRECTORY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
