name: Docker image push to Docker Hub.

on:
  push:
    branches: [ "demo" ]
  #pull_request:
    #branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Docker Hub login
      env:
        DOCKER_USER: yuria
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yuria/devops-git-actions
    - name: Docker Push
      run:
        docker push yuria/devops-git-actions